# Copyright (c) 2024 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: kkasperczyk
      url-base: https://github.com/kkasperczyk-no
    - name: ArekBalysNordic
      url-base: https://github.com/ArekBalysNordic

  projects:
    - name: nrf
      remote: ArekBalysNordic
      repo-path: sdk-nrf
      revision: rd_callbacks_deduplication
      import: true
